blank_issues_enabled: true
contact_links:
  - name: Test Framework Issue
    url: https://github.com/nunit/nunit/issues/new
    about: For issues encountered when using the test framework (and not specifically with documentation)
  - name: Console Runner Issue
    url: https://github.com/nunit/nunit-console/issues/new
    about: For issues encountered when using the console runner (and not specifically with documentation)
  - name: VS Test Adapter
    url: https://github.com/nunit/nunit3-vs-adapter/issues/new
    about: For issues encountered when using the NUnit Visual Studio Test Adapter (and not specifically with documentation)
  - name: Issue while using another NUnit project / component (and not specifically with documentation)
    url: https://github.com/nunit#org-repositories
    about: Please find the appropriate repository at this list and file an issue there.
  - name: Definitely docs-related
    url: https://github.com/nunit/docs/issues/new
    about: We'd love to hear about it!
  
  
