name: NUnit Documentation Build Process

jobs:
    build_docfx:
      on:
        push:
          branches:
            - master
        pull_request:
          branches:
            - master
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        name: Check out the code
      - uses: nikeee/docfx-action@master
        name: Build Documentation
        with:
          args: docs/docfx.json